// src/Renovation/journalMaj.js — Contenu du « Journal des MAJ ».
//
// Une entrée = une mise à jour visible pour les utilisateurs, expliquée en
// langage courant. Le composant PageJournalMaj.jsx lit ce fichier tel quel :
// pour publier une nouvelle mise à jour, il suffit d'ajouter une entrée EN
// TÊTE du tableau ci-dessous (les entrées sont triées par date décroissante
// à l'affichage, mais autant garder le fichier lisible).
//
// Champs :
//   date   : "AAAA-MM-JJ" (date de mise en ligne)
//   type   : "nouveaute" | "amelioration" | "correctif"
//   titre  : une ligne, ce que l'utilisateur retient
//   pages  : [{ id, label }] pages de l'appli concernées (id = ids de access.js)
//            — laisser [] si c'est transversal (toute l'appli)
//   quoi   : à quoi ça sert (le bénéfice, pour qui)
//   comment: comment ça fonctionne (où cliquer, ce qui se passe)

export const TYPES_MAJ = {
  nouveaute:    { label: "Nouveauté",    color: "#22c55e" },
  amelioration: { label: "Amélioration", color: "#4db8ff" },
  correctif:    { label: "Correctif",    color: "#f59e0b" },
};

export const JOURNAL_MAJ = [
  {
    date: "2026-09-17",
    type: "nouveaute",
    titre: "La cadence Profero part maintenant avec l'ouvrage envoyé dans ProGBat",
    pages: [{ id: "bibliotheque", label: "Bibliothèque" }, { id: "admin", label: "Réglages" }],
    quoi: "Jusqu'ici, un ouvrage envoyé dans ProGBat n'emportait que ses prix. ProGBat, n'ayant aucun temps pour cet ouvrage, en reconstituait un à partir du prix : les devis affichaient donc des heures qui ne correspondaient pas à la bibliothèque Profero. Désormais la cadence est envoyée avec l'ouvrage, et les temps concordent.",
    comment: "Sur la fiche d'un ouvrage, « Créer sur ProGBat » demande, en plus de la famille, la main-d'œuvre ProGBat qui portera les heures (le choix est automatique s'il n'y en a qu'une). L'aperçu annonce la cadence exacte avant toute écriture. Le prix de vente reste celui de Profero : ProGBat ne le recalcule pas. Pour un ouvrage DÉJÀ envoyé dans ProGBat, le bouton « Vérifier la cadence ProGBat » permet de lui poser sa cadence, à une condition stricte : sa composition ProGBat doit être vide. Si l'ouvrage a déjà une composition dans ProGBat, Profero n'y touche pas et le dit — c'est ProGBat qui fait foi dans ce cas. Les matériaux ne sont pas encore envoyés : cela demandera d'abord une correspondance entre les matériaux Profero et les éléments ProGBat.",
  },
  {
    date: "2026-09-17",
    type: "nouveaute",
    titre: "Espace ouvrier : les chantiers sont maintenant rangés par opération",
    pages: [],
    quoi: "Sur le téléphone, l'onglet « Chantiers » de l'espace ouvrier s'appelle désormais « Opérations » et présente d'abord les opérations — l'immeuble ou l'adresse — au lieu d'une longue liste de tous les chantiers mélangés. Sur un programme de plusieurs logements, on trouve le bon bien plus vite.",
    comment: "Onglet « Opérations » : chaque opération montre sa couleur, son adresse, son nombre de chantiers et où ils en sont. On l'ouvre pour voir l'adresse, l'itinéraire Maps/Waze et la liste de ses chantiers ; on ouvre ensuite un chantier pour retrouver exactement l'écran habituel — plans, documents et heures par ouvrage, rien n'y a changé. Les chantiers qui ne sont rattachés à aucune opération restent accessibles dans la section « Chantiers hors opération », en bas. Le bouton retour ramène à l'opération d'où l'on vient. Le rattachement d'un chantier à une opération se règle côté bureau, dans Réglages → Opérations.",
  },
  {
    date: "2026-09-17",
    type: "correctif",
    titre: "Un compte désactivé n'a plus accès aux données",
    pages: [],
    quoi: "Jusqu'ici, désactiver un compte dans Réglages → Utilisateurs l'empêchait d'utiliser l'application, mais ne lui retirait pas ses droits sur les données. Et un compte de connexion sans fiche utilisateur obtenait par défaut les droits du bureau — donc l'accès aux salaires, aux chiffrages et aux factures. Les deux trous sont fermés.",
    comment: "Rien ne change pour les comptes actifs : un ouvrier garde son espace, le bureau garde tous ses accès. Désormais, un compte désactivé ou sans fiche utilisateur n'a plus aucun accès, ni en lecture ni en écriture. Conséquence pratique : pour retirer l'accès à quelqu'un, décochez « actif » sur sa fiche — ne supprimez pas sa fiche, et si elle a déjà été supprimée, recréez-la puis désactivez-la. Réactiver un compte lui rend ses accès immédiatement.",
  },
  {
    date: "2026-09-17",
    type: "nouveaute",
    titre: "Créer un ouvrage dans ProGBat depuis sa fiche, dans la famille de votre choix",
    pages: [{ id: "bibliotheque", label: "Bibliothèque" }],
    quoi: "Un ouvrage créé dans la bibliothèque Profero peut maintenant être envoyé dans ProGBat depuis sa propre fiche, un par un, sans attendre ni déclencher la synchronisation de toute la bibliothèque depuis les Réglages. Il arrive directement dans une de vos familles ProGBat existantes : plus de dossier d'attente à reclasser ensuite. La synchronisation globale des Réglages demande la même chose.",
    comment: "Ouvrir l'ouvrage dans la Bibliothèque : en bas de la fiche, « Créer sur ProGBat » vérifie d'abord la situation sans rien écrire, puis propose la famille ProGBat de destination — la liste ne contient que des familles qui existent déjà dans ProGBat, et celle qui porte le nom de la catégorie de l'ouvrage est présélectionnée. L'aperçu affiche alors ce qui sera fait : création dans cette famille avec l'unité, le prix d'achat, le prix de vente et la TVA, ou simple liaison si un ouvrage ProGBat porte déjà ce code. L'écriture n'a lieu qu'après confirmation. Si l'ouvrage est incomplet (code, unité, cadence, matériaux, prix), la fiche dit précisément ce qui manque. Une fois envoyé, l'ouvrage affiche son numéro ProGBat ; les ouvrages non encore envoyés portent la mention « Pas sur ProGBat » dans la liste. Aucun ouvrage ni aucune famille existante n'est modifié, créé ou supprimé dans ProGBat.",
  },
  {
    date: "2026-09-17",
    type: "nouveaute",
    titre: "Les factures ProGBat d'un chantier s'affichent sur sa fiche",
    pages: [{ id: "chantiers", label: "Chantiers" }],
    quoi: "Le bloc « Facturation client » d'une fiche chantier montre maintenant les factures venues de ProGBat, avec ce qui a été facturé, ce qui a été encaissé et ce qui reste dû. Plus besoin d'ouvrir ProGBat pour savoir où en est une facture.",
    comment: "Fiche chantier, bloc « Facturation client », section « Factures ProGBat ». Chaque ligne indique sa nature (facture, acompte ou avoir), son montant TTC, les règlements reçus et son état — non réglée, partiellement réglée, réglée, ou l'équivalent pour un avoir. Le détail des règlements s'ouvre au clic. Tout y est en lecture seule : ces factures viennent de la synchronisation (Réglages → Fournisseurs) et ne se modifient pas ici. L'échéancier prévisionnel au-dessus continue de ne concerner que les factures déposées à la main.",
  },
  {
    date: "2026-09-17",
    type: "nouveaute",
    titre: "Import des factures et règlements ProGBat, avec prévisualisation avant écriture",
    pages: [{ id: "admin", label: "Réglages" }],
    quoi: "Les factures émises et les règlements encaissés dans ProGBat peuvent maintenant être importés dans le registre de facturation, sans aucune ressaisie. L'import est toujours précédé d'une prévisualisation qui annonce exactement ce qui sera créé, mis à jour ou laissé de côté.",
    comment: "Réglages → Fournisseurs, carte « Connexion ProGBat ». « Analyser la synchronisation » affiche ce qui serait importé sans rien écrire. Si l'analyse est complète et sans anomalie, un bouton « Synchroniser avec ProGBat » apparaît : il demande de saisir SYNCHRONISER, puis écrit. L'import ne modifie jamais ProGBat, ne touche pas aux factures saisies à la main, et ne reprend pas une échéance corrigée manuellement. Les factures dont le chantier ProGBat n'est pas encore rattaché sont ignorées et comptées : rattachez-les sur la fiche chantier puis relancez.",
  },
  {
    date: "2026-09-16",
    type: "nouveaute",
    titre: "Rattachement des chantiers ProGBat pour préparer la synchronisation automatique des factures",
    pages: [{ id: "chantiers", label: "Chantiers" }],
    quoi: "Le bloc « Facturation client » d'une fiche chantier permet maintenant d'indiquer quels chantiers ProGBat correspondent à ce chantier Profero. C'est ce lien qui permettra aux factures et avenants ProGBat d'être rattachés automatiquement au bon chantier.",
    comment: "Dans « Chantiers ProGBat associés » : les chantiers portent le code exact de ProGBat, celui de sa colonne « Code » (par exemple « #83 TROTTIER - T2 - R+2 »), et se cherchent par ce code, par leur libellé ou par leur numéro ; on choisit dans la liste, puis « Rattacher ». Un chantier Profero peut recevoir plusieurs chantiers ProGBat ; un chantier ProGBat ne peut appartenir qu'à un seul chantier Profero (la liste indique clairement ceux déjà pris ailleurs). Rien n'est jamais rapproché tout seul par ressemblance de nom. L'ancien rattachement par devis reste disponible, replié sous « Rattachement de secours par devis », pour les rares factures ProGBat sans chantier.",
  },
  {
    date: "2026-09-18",
    type: "nouveaute",
    titre: "Facturation client : importez la facture, l'échéance est reconnue et le cycle de vie se coche",
    pages: [{ id: "chantiers", label: "Chantiers" }, { id: "admin", label: "Réglages" }],
    quoi: "La fiche d'un chantier a désormais un bloc « Facturation client ». La personne en charge de la facturation y dépose les factures au fur et à mesure : le montant, le numéro et la date sont lus automatiquement sur le PDF, et l'application reconnaît de quelle échéance il s'agit en rapportant le montant au marché — facture d'acompte à 50 %, de démarrage à 20 %, de situation n° 1 à 15 %, n° 2 à 10 %, solde à 5 %. Elle affiche à tout moment ce qui est facturé, ce qui est encaissé et ce qu'il reste à facturer, et signale l'échéance qui devient exigible (à la signature, à un seuil d'avancement, à la réception) avec un email aux rôles choisis.",
    comment: "Bouton « Importer une facture » (ou « Importer la facture » sur une échéance précise) : le document part dans l'espace documents du chantier, il est lu, puis une fenêtre montre ce qui a été relevé et l'échéance proposée AVEC la raison du rapprochement — tout est modifiable avant d'enregistrer, et un doublon de numéro est signalé. Rien n'est jamais coché sur la seule foi de la lecture automatique. Une facture a deux états distincts : émise à l'import, puis encaissée quand l'argent est arrivé (bouton « Marquer encaissée », date et montant reçus) — et c'est l'encaissement de l'acompte, pas son émission, qui coche « Acompte encaissé » dans la frise du cycle de vie. Les autres échéances apparaissent dans la phase Travaux de la frise et s'y cochent toutes seules dès que leur facture est importée : elles remplacent les anciennes « factures de situation 25/50/75/100 % », qui se cochaient à la main sans pièce jointe. L'échéancier par défaut se règle dans Réglages → Facturation (libellés, pourcentages, déclencheurs, destinataires des alertes) et reste ajustable chantier par chantier ; un échéancier enregistré sur un chantier y est figé et ne bouge plus si le réglage général change. Si le montant du marché n'est pas connu, le bloc le dit et laisse choisir l'échéance à la main.",
  },
  {
    date: "2026-09-17",
    type: "amelioration",
    titre: "Coefficient et taux horaire de vente : champs libres au lieu des listes",
    pages: [{ id: "bibliotheque", label: "Biblio. ouvrages" }, { id: "info-client", label: "Chiffrage" }],
    quoi: "Il fallait jusqu'ici choisir le coefficient de vente et le taux horaire dans une liste déroulante, et donc créer une entrée dans les Réglages avant de pouvoir l'utiliser. Aux trois endroits où ces deux valeurs se règlent — la fiche d'un ouvrage, les conditions globales d'un chiffrage et la dérogation d'une ligne de devis — la liste est remplacée par un champ dans lequel on tape la valeur voulue (1,42 ou 87 €/h, sans rien créer au préalable).",
    comment: "Chaque champ s'ouvre pré-rempli avec la valeur par défaut des Réglages (ou celle déjà en place) et reste entièrement modifiable ; un bouton « Défaut » permet d'y revenir. Les Réglages → Taux horaires restent utiles : ils ne servent plus qu'à fixer ces valeurs proposées, ils n'imposent plus de choix. Tout le reste est inchangé : la valeur reste FIGÉE là où elle est enregistrée (une modification ultérieure des Réglages n'a aucun effet rétroactif), la modale d'une ligne montre toujours l'aperçu avant/après avant d'appliquer, et les prix comme les marges restent calculés par le serveur depuis les seules données figées de la ligne. Les ouvrages existants ont récupéré la valeur du coefficient et du taux qu'ils utilisaient : aucun prix n'a bougé.",
  },
  {
    date: "2026-09-16",
    type: "nouveaute",
    titre: "Chiffrage : « Modifier matériaux » ouvre l'ouvrage dans la bibliothèque et réactualise le devis",
    pages: [{ id: "info-client", label: "Chiffrage" }, { id: "bibliotheque", label: "Biblio. ouvrages" }],
    quoi: "Quand les matériaux d'un ouvrage doivent être corrigés (une quantité qui n'est pas la bonne, un matériau oublié), il fallait quitter le chiffrage, retrouver l'ouvrage dans la bibliothèque à la main, le modifier, revenir au chiffrage, resélectionner le bon client puis actualiser chaque ligne une par une. Ce chemin est maintenant fait pour vous : un bouton sur la ligne, la correction, un bouton pour revenir — et le devis est à jour.",
    comment: "Onglet Ouvrages du Chiffrage : chaque ligne issue de la bibliothèque porte un bouton « Modifier matériaux » qui ouvre directement la fiche de cet ouvrage dans la page Bibliothèque (filtres levés, fiche dépliée). Un bandeau y rappelle d'enregistrer la fiche et propose « Revenir au chiffrage ». Au retour, on retombe sur le bon client, onglet Ouvrages, et TOUTES les lignes de ce devis issues de cet ouvrage sont recalculées et réenregistrées automatiquement ; un bandeau indique ce qui a changé. Les autres chiffrages ne sont jamais touchés. Un chiffrage terminé (devis envoyé, signé ou abandonné) garde ses prix figés : le bandeau signale l'écart sans rien modifier, et le bouton ↻ de la ligne permet d'actualiser quand même, après confirmation.",
  },
  {
    date: "2026-09-16",
    type: "correctif",
    titre: "Chantiers : les documents du cycle de vie s'envoient et s'ouvrent à nouveau",
    pages: [{ id: "chantiers", label: "Chantiers" }],
    quoi: "L'import d'un document sur une étape du cycle de vie (devis signé, plans, PV de réception, DOE, pièce jointe) pouvait échouer avec un message affirmant que l'espace de stockage n'existait pas. Le stockage était bien en place : la demande partait sans la preuve que vous étiez connecté, et le serveur la refusait. Le fichier semblait alors impossible à joindre alors que tout le reste de la page fonctionnait normalement.",
    comment: "L'envoi et l'ouverture d'un document emportent maintenant explicitement votre session, avec une seconde tentative automatique après renouvellement si le serveur refuse la première. Et si la session est réellement expirée, le message le dit clairement (« Session expirée : reconnectez-vous puis réessayez ») au lieu d'accuser le stockage.",
  },
  {
    date: "2026-09-16",
    type: "nouveaute",
    titre: "Chiffrage : coefficient et taux horaire modifiables sur un seul ouvrage",
    pages: [{ id: "info-client", label: "Chiffrage" }],
    quoi: "Jusqu'ici, le coefficient et le taux horaire de vente se choisissaient soit ouvrage par ouvrage dans la bibliothèque, soit globalement pour tout le chiffrage. Il est désormais possible de déroger sur UNE SEULE ligne du devis : tout le chiffrage peut rester à 1,30 et 70 €/h pendant qu'un ouvrage particulier passe à 1,50 et 80 €/h. Les autres lignes, les autres chiffrages et la fiche de l'ouvrage dans la bibliothèque ne bougent pas, et la valeur choisie est figée sur la ligne — un changement ultérieur dans les Réglages ne la modifiera pas.",
    comment: "Sur chaque ligne du devis, un bouton « réglages » (curseurs) ouvre « Conditions de vente de cette ligne ». Deux listes indépendantes : « Coefficient de vente appliqué » et « Taux horaire de vente appliqué ». Pour chacune, trois possibilités : hériter du chiffrage, forcer le paramètre de l'ouvrage (même si le chiffrage impose un coefficient global), ou choisir une valeur précise parmi celles des Réglages. La valeur réellement appliquée et son origine sont affichées en clair, et un aperçu montre l'ancien et le nouveau coefficient, taux, prix unitaire et marge AVANT toute validation — rien n'est enregistré tant qu'on n'a pas cliqué sur « Appliquer à cet ouvrage ». Les lignes dérogatoires portent un badge « Conditions spécifiques ». Une ligne à prix saisi à la main, ou calculée avec l'ancienne formule, demande une confirmation explicite supplémentaire (l'ancien prix est conservé dans l'historique) ; si les données de calcul figées manquent, l'opération est bloquée avec l'explication de ce qui manque. Enfin, quand on change les conditions globales du chiffrage, les lignes dérogatoires ne sont plus touchées : le récapitulatif indique combien de coefficients et de taux spécifiques ont été conservés.",
  },
  {
    date: "2026-09-16",
    type: "correctif",
    titre: "Chiffrage : la saisie d'une ligne ne revient plus en arrière, et les nombres se tapent normalement partout",
    pages: [{ id: "info-client", label: "Chiffrage" }, { id: "phasage", label: "Phasage" }, { id: "bibliotheque", label: "Biblio. ouvrages" }, { id: "dashboard-analyse", label: "Dashboard Analyse" }],
    quoi: "Deux gênes de saisie sont corrigées. 1) Sur le Chiffrage, la zone, la quantité, le prix d'une ligne et les champs d'une cote pouvaient revenir à une version précédente en pleine frappe : l'enregistrement automatique partait pendant une pause, et sa confirmation revenait écraser les caractères tapés entre-temps. 2) Partout dans l'application, les champs de nombres refusaient les saisies intermédiaires : impossible de taper une virgule, un chiffre après la virgule ou de commencer par un zéro sans que le champ se remette à zéro ou efface la frappe.",
    comment: "Chiffrage : chaque champ d'une ligne en cours de saisie est protégé le temps de son enregistrement ; les modifications faites au même moment par un collègue sur les AUTRES champs de la ligne continuent d'arriver normalement. Nombres : un champ de saisie unique est désormais utilisé pour tous les nombres (heures, quantités, prix, cadences, pourcentages, budgets Invest…). Il affiche exactement ce qui est tapé tant qu'on est dedans, accepte la virgule comme le point, propose le pavé numérique sur téléphone, et remet la valeur au propre en sortant du champ (« 05 » devient « 5 »). Il ne corrige jamais la valeur en douce : les bornes (0 à 100 %, quantité minimale…) restent celles de chaque écran.",
  },
  {
    date: "2026-09-16",
    type: "correctif",
    titre: "Saisie qui « revenait en arrière » : texte et nombres restent désormais tels qu'on les tape",
    pages: [{ id: "admin", label: "Réglages" }, { id: "bibliotheque", label: "Biblio. ouvrages" }, { id: "phasage", label: "Phasage" }, { id: "commandes", label: "Commandes" }],
    quoi: "À plusieurs endroits, un champ pouvait revenir tout seul à une version précédente pendant la frappe : quelques caractères disparaissaient, ou le champ perdait le curseur au milieu d'un mot. En cause, l'enregistrement à chaque caractère : la valeur partie une demi-seconde plus tôt revenait par le temps réel et écrasait ce qui venait d'être tapé. Une modification en attente pouvait aussi être perdue en passant d'un réglage à un autre.",
    comment: "Réglages : le nom d'un chantier, les taux horaires, le taux MO prévisionnel, la TVA et l'acompte par défaut ne sont enregistrés qu'une fois la saisie retombée, et l'écho de notre propre enregistrement ne revient plus écraser le champ. Chaque bloc de réglages (modèles d'email, phases, lots, groupes types, équipes, opérations, exceptions d'heures) a désormais sa propre sauvegarde différée : éditer l'un n'annule plus la sauvegarde de l'autre, et quitter la page écrit ce qui restait en attente. Bibliothèque : une fiche ouvrage ouverte n'est plus remplacée par un rafraîchissement temps réel — la mise à jour est appliquée à la fermeture de la fiche. Phasage → Suivi direction : marge cible, taux FG, seuil de prime et prime se saisissent normalement (décimales comprises) et ne s'enregistrent qu'à la fin de la saisie. Commandes, Référentiels de vente et Équipe : les rafraîchissements en arrière-plan ne relancent plus l'écran de chargement, qui faisait disparaître la ligne en cours d'édition.",
  },
  {
    date: "2026-09-16",
    type: "nouveaute",
    titre: "Import ponctuel des cadences ProGBat vers la bibliothèque : analyse, aperçu, confirmation, puis Profero source de vérité",
    pages: [{ id: "admin", label: "Réglages" }, { id: "bibliotheque", label: "Biblio. ouvrages" }],
    quoi: "Les cadences (heures de main-d'œuvre par unité d'ouvrage) enregistrées dans ProGBat peuvent être importées une fois dans la bibliothèque Profero, ouvrage par ouvrage, uniquement via la liaison existante (identifiant ProGBat de la fiche). La cadence ProGBat est la somme des heures des composants de main-d'œuvre horaires de la composition développée de l'ouvrage ; elle n'est jamais déduite d'un prix, d'un libellé ou d'un coût. Une cadence absente, nulle, négative ou ambiguë n'écrase jamais une cadence Profero. Après l'import, Profero est la seule source de vérité : rien n'est réimporté automatiquement, aucune tâche planifiée, et toute modification ultérieure se fait dans la Bibliothèque (la provenance repasse alors à « Profero »).",
    comment: "Réglages → Outils → Maintenance → bloc « Importer les cadences depuis ProGBat » (administrateurs et conducteurs). 1. « Analyser les cadences » : lecture seule, tableau Code / Ouvrage / ID ProGBat / Cadence Profero / Cadence ProGBat / Écart / Statut, filtres (tous, changements, identiques, anomalies, non liés), synthèse chiffrée, écarts importants (> 50 % ou ×/÷ 2) surlignés, plan figé côté serveur avec un hash, valable 30 minutes. 2. « Confirmer l'import » : fenêtre récapitulative explicite (ouvrages mis à jour, identiques, non modifiés ; aucun chiffrage recalculé ; rien modifié dans ProGBat) puis « Importer les cadences ». Le navigateur n'envoie que l'identifiant du plan et son hash : le serveur revalide chaque liaison et chaque cadence et applique tout en une seule transaction (tout ou rien ; refus si une cadence ou une liaison a changé entre-temps, double-clic ou second onglet). Historique complet (ancienne et nouvelle cadence, méthode, utilisateur, date) conservé en lecture seule. Les chiffrages existants ne bougent pas ; les nouvelles lignes et l'actualisation volontaire d'une ligne utilisent la nouvelle cadence. La fiche ouvrage affiche « import ProGBat » à côté de la cadence importée.",
  },
  {
    date: "2026-09-16",
    type: "nouveaute",
    titre: "Conditions de vente d'un chiffrage : coefficient et/ou taux horaire global, figés sur le chiffrage",
    pages: [{ id: "info-client", label: "Chiffrage" }],
    quoi: "Chaque chiffrage peut imposer, indépendamment, un coefficient de vente global et/ou un taux horaire global à toutes ses lignes, à la place des paramètres de chaque ouvrage (client négocié, remise commerciale…). Les valeurs sont figées sur le chiffrage : modifier un coefficient ou un taux dans les Réglages ne change rien tant qu'on ne l'applique pas volontairement. Chaque ligne garde ses paramètres d'origine (ceux de l'ouvrage) à côté des paramètres réellement appliqués, ce qui permet de revenir aux paramètres de chaque ouvrage sans rien inventer. La bibliothèque, les coûts, quantités et cadences ne sont jamais modifiés.",
    comment: "Chiffrage → onglet Ouvrages → bloc « Conditions de vente du chiffrage » → Modifier : choisir « Utiliser le coefficient de chaque ouvrage » ou « Appliquer un coefficient global » (liste des coefficients actifs), idem pour le taux horaire, puis « Simuler ». Une fenêtre montre l'ancien et le nouveau paramétrage, le nombre de lignes recalculées, le total HT et la marge avant / après, l'écart et les lignes non recalculables (anciennes lignes à prix saisi ou de l'ancienne formule, laissées telles quelles). Rien n'est enregistré avant « Appliquer les conditions » ; l'application est refusée si le chiffrage a changé entre-temps (double clic, autre onglet, autre utilisateur). Les lignes concernées affichent le coefficient et le taux appliqués (badge bleu « global ») et, dans le détail du prix figé, la valeur d'origine de l'ouvrage. Un chiffrage signé n'est plus modifiable ; un brouillon ProGBat déjà créé n'est jamais actualisé (avertissement). L'historique des changements (qui, quand, ancien/nouveau, totaux, marges) est consultable dans le bloc.",
  },
  {
    date: "2026-09-16",
    type: "nouveaute",
    titre: "Coefficients de vente configurables : le coefficient d'un ouvrage se choisit dans une liste, comme le taux horaire",
    pages: [{ id: "admin", label: "Réglages" }, { id: "bibliotheque", label: "Biblio. ouvrages" }, { id: "info-client", label: "Chiffrage" }],
    quoi: "La saisie libre du coefficient dans chaque fiche ouvrage est remplacée par une liste de coefficients partagés (Coefficient standard — 1,50 créé et affecté aux 105 ouvrages existants, y compris ceux qui portaient un autre coefficient). Prix matériaux = coût matériaux × coefficient choisi ; la main-d'œuvre garde son taux horaire. Modifier un coefficient recalcule le prix des ouvrages qui l'utilisent pour les futurs chiffrages ; les lignes et devis déjà figés gardent leur coefficient et leur prix.",
    comment: "Réglages → Taux horaires → « Coefficients de vente » (administrateurs) : créer un coefficient, modifier son libellé ou sa valeur (un avertissement indique le nombre réel d'ouvrages concernés), choisir le coefficient par défaut des nouveaux ouvrages, désactiver ou réactiver (jamais supprimé ; un coefficient désactivé reste sur les ouvrages qui l'utilisent, affiché « désactivé »). Bibliothèque : liste déroulante obligatoire « Coefficient de vente », présélectionnée sur le défaut à la création et reprise à la duplication, avec le détail « Matériaux : 100,00 € × 1,50 = 150,00 € HT ».",
  },
  {
    date: "2026-09-16",
    type: "nouveaute",
    titre: "Taux horaires de main-d'œuvre configurables : le prix MO d'un ouvrage = cadence × taux choisi",
    pages: [{ id: "admin", label: "Réglages" }, { id: "bibliotheque", label: "Biblio. ouvrages" }, { id: "info-client", label: "Chiffrage" }],
    quoi: "L'unique taux global de main-d'œuvre est remplacé par une liste de taux de vente (Taux standard — 80,00 € HT/h créé et affecté à tous les ouvrages existants). Chaque fiche ouvrage choisit son taux dans une liste déroulante ; le prix de vente devient : matériaux × coefficient + cadence × taux horaire. Le coefficient ne s'applique donc plus à la main-d'œuvre. Les devis et lignes déjà figés gardent leur prix et leur taux historique.",
    comment: "Réglages → Taux horaires → « Taux horaires de main-d'œuvre » (administrateurs) : ajouter un taux, modifier son libellé ou sa valeur (un avertissement rappelle que seuls les futurs chiffrages changent), choisir le taux par défaut des nouveaux ouvrages, désactiver ou réactiver un taux (jamais supprimé ; un taux désactivé reste sur les ouvrages qui l'utilisent, affiché « désactivé »). Bibliothèque : champ obligatoire « Taux horaire de main-d'œuvre » dans chaque fiche, présélectionné sur le taux par défaut à la création, avec le détail « 2,50 h × 80,00 €/h = 200,00 € HT ». Le coût horaire chargé (Taux MO prévisionnel) ne sert plus qu'à la marge.",
  },
  {
    date: "2026-09-15",
    type: "nouveaute",
    titre: "Adresses : suggestions automatiques dans tous les champs d'adresse",
    pages: [],
    quoi: "Plus besoin de taper une adresse en entier ni de chercher le code postal : dès trois caractères, l'appli propose les adresses correspondantes (Base Adresse Nationale, service gratuit de l'État). Un clic sur la suggestion remplit d'un coup la rue, le code postal et la ville (et les coordonnées GPS pour les biens Invest).",
    comment: "Dans n'importe quel champ d'adresse (chantier et facturation du chiffrage, opérations, compte-rendu d'équipe, biens, visites, annonces, structuration, urbanisme, état des lieux) : taper par exemple « 12 rue Paul » puis choisir « 12 Rue Paul Langevin 49240 Avrillé » à la souris ou avec les flèches + Entrée. Les champs Ville et Code postal proposent aussi les communes (taper « Avril » ou « 49240 »). La saisie libre reste possible, y compris pour une adresse hors de France.",
  },
  {
    date: "15/09/2026",
    titre: "Classement sécurisé des ouvrages ProGBat",
    quoi: "L’inventaire ProGBat peut maintenant préparer puis exécuter le classement des ouvrages déjà liés dans les familles métier correspondant aux préfixes de code configurés dans les lots Profero.",
    comment: "Réglages → Inventaire de la bibliothèque → Préparer le classement. Une simulation affiche les familles existantes à activer, celles à créer, les ouvrages à déplacer et les préfixes non configurés laissés dans Ouvrages V2. Après confirmation, seuls l’activation de la famille pour les ouvrages puis le champ families des ouvrages sont modifiés dans ProGBat : aucun prix, libellé, code, composant ou ouvrage n’est créé ou supprimé.",
  },
  // ── SEPTEMBRE 2026 ─────────────────────────────────────────────────────────
  {
    date: "2026-09-15",
    type: "nouveaute",
    titre: "Bibliothèque : première synchronisation sécurisée vers ProGBat",
    pages: [{ id: "admin", label: "Réglages" }, { id: "bibliotheque", label: "Bibliothèque" }],
    quoi: "La bibliothèque Profero peut maintenant enregistrer les correspondances dont le code métier est unique dans ProGBat et créer les ouvrages réellement absents dans le dossier « Ouvrages V2 ». Cette première version est volontairement conservatrice : elle ne modifie ni ne supprime aucun ouvrage ProGBat existant et ne crée pas encore les matériaux/compositions détaillés.",
    comment: "Réglages → Outils → Maintenance → Inventaire de la bibliothèque : lancer « Analyser », puis « Préparer la synchronisation ». Le serveur recharge les deux bibliothèques, contrôle le dossier cible, les unités, la TVA et les prix, puis affiche la liste exacte des liaisons et créations. « Synchroniser » ouvre une dernière confirmation. Une réservation en base empêche les doubles créations ; un délai, une coupure réseau ou une erreur ProGBat 5xx bloque l’ouvrage en état incertain jusqu’à vérification manuelle.",
  },
  {
    date: "2026-09-14",
    type: "nouveaute",
    titre: "Chiffrage : création d'un devis brouillon dans ProGBat, lignes liées à la bibliothèque ProGBat",
    pages: [{ id: "info-client", label: "Chiffrage" }],
    quoi: "Un logement Profero entièrement valide peut désormais devenir un devis BROUILLON dans ProGBat, en un clic confirmé. Le serveur recharge le projet et ses lignes, reconstruit lui-même le devis (client ou client ProGBat existant, chantier, objet, validité, TVA convertie en identifiants ProGBat, LOT → ZONE → OUVRAGES avec les prix figés), refait tous les contrôles et compare l'empreinte du devis à celle de l'aperçu confirmé avant d'appeler ProGBat. Un même logement ne peut jamais créer deux devis : double clic, rafraîchissement ou second onglet sont refusés. Chaque ligne du devis est désormais liée à l'ouvrage correspondant de la bibliothèque ProGBat (sa composition est chargée dans le devis) tout en gardant le prix, l'unité, la TVA et le libellé figés par Profero ; si un seul ouvrage du chiffrage n'est pas lié, ou si sa fiche a disparu dans ProGBat, la création est bloquée et la ligne est signalée. Le devis créé n'est ni finalisé ni envoyé au client.",
    comment: "Chiffrage → onglet Ouvrages → « Aperçu ProGBat » : l'aperçu est reconstruit par le serveur (bandeau bleu). Quand il est valide, le bouton « Créer le brouillon dans ProGBat » ouvre une confirmation (logement, client, objet, lots, zones, ouvrages, HT, TVA, TTC). Après réussite, « Devis brouillon ProGBat créé » s'affiche avec l'identifiant, la date et l'utilisateur ; une relecture ProGBat confirme la présence du brouillon sans jamais le recréer. Si le chiffrage change ensuite, un message l'indique (la mise à jour d'un brouillon existant viendra dans une phase séparée). En cas d'état incertain (délai dépassé, réponse incomplète), un avertissement rouge demande une vérification manuelle dans ProGBat et interdit toute nouvelle tentative. La ligne « Ouvrages liés à la bibliothèque ProGBat : n / n » et la mention « Ouvrage ProGBat #… » ou « Non lié à ProGBat » sur chaque ligne indiquent l'état des liaisons (elles se règlent via la synchronisation de la bibliothèque dans Réglages). Réservé au bureau.",
  },
  {
    date: "2026-09-14",
    type: "nouveaute",
    titre: "Chiffrage : aperçu du futur devis ProGBat (aucun envoi)",
    pages: [{ id: "info-client", label: "Chiffrage" }],
    quoi: "Avant de créer un jour des devis dans ProGBat depuis Profero, on peut voir exactement ce qui serait transmis pour un logement : client (ou client ProGBat existant), chantier, objet, validité, taux de TVA convertis en identifiants ProGBat, puis le devis organisé en LOT → ZONE → OUVRAGES avec les quantités, unités et prix de vente HT figés dans le chiffrage. Les contrôles bloquants (client, adresse, référence du logement, objet, validité, zone, quantité, prix, TVA, anciennes lignes sans snapshot, total différent) et les avertissements sont listés, et le total HT est comparé au centime avec celui du chiffrage. Aucun coût, coefficient ni marge ne figure dans ce qui serait envoyé.",
    comment: "Chiffrage → onglet Ouvrages → bouton « Aperçu ProGBat » à côté de « Aperçu du devis ». La fenêtre lit uniquement les taux de TVA ProGBat (lecture seule, côté serveur) et affiche le payload JSON dans une section technique repliée. Rien n'est envoyé à ProGBat : il n'existe aucun bouton d'envoi dans cette version. Réservé au bureau.",
  },
  {
    date: "2026-09-14",
    type: "nouveaute",
    titre: "Réglages : inventaire de la bibliothèque ProGBat (simulation en lecture seule)",
    pages: [{ id: "admin", label: "Réglages" }, { id: "bibliotheque", label: "Bibliothèque" }],
    quoi: "Avant toute synchronisation réelle, on peut comparer la bibliothèque d'ouvrages Profero avec celle de ProGBat sans rien modifier. L'analyse classe chaque ouvrage Profero : déjà lié, code identique à confirmer, ambigu (plusieurs ouvrages ProGBat portent le même code), libellé identique à examiner, ou nouveau à créer. Elle signale aussi les ouvrages présents uniquement dans ProGBat et, pour chaque ouvrage Profero, ce qui manque pour qu'il soit prêt à synchroniser (code, unité, cadence, matériaux et prix, coefficient de vente, TVA).",
    comment: "Réglages → Outils → Maintenance → carte « Inventaire de la bibliothèque » → « Analyser la bibliothèque ». Compteurs par statut cliquables pour filtrer, filtre « Bloqués », tableau code / libellé / id ProGBat / correspondance proposée / statut / prêt / blocages, puis liste des ouvrages ProGBat non liés. Aucune correspondance n'est enregistrée et aucun bouton de synchronisation n'existe encore : c'est une simulation, le bandeau bleu le rappelle. Réservé au bureau.",
  },
  {
    date: "2026-09-14",
    type: "nouveaute",
    titre: "Réglages : test de la connexion ProGBat (lecture seule)",
    pages: [{ id: "admin", label: "Réglages" }],
    quoi: "Premier pas vers la liaison avec ProGBat (logiciel de devis). Avant toute synchronisation de la bibliothèque ou création de devis, un bouton permet de vérifier que le jeton ProGBat enregistré côté serveur est valide et qu'il correspond bien au compte Profero Rénovation. Rien n'est créé ni modifié, ni dans ProGBat ni dans l'application : c'est une simple lecture du profil.",
    comment: "Réglages → Outils → Maintenance → carte « Connexion ProGBat » → « Tester la connexion ». Le résultat affiche le compte ProGBat reconnu, le nom de l'entreprise quand il est disponible et le code HTTP. Le nom de l'entreprise peut rester « non disponible » tant que l'accès ProGBat n'inclut pas le droit de lecture des comptes : cela n'empêche pas le test de réussir. Réservé au bureau (page Réglages), jamais visible dans l'espace ouvrier.",
  },
  {
    date: "2026-09-14",
    type: "amelioration",
    titre: "Bibliothèque : le prix se règle par coefficient (× coût), la marge est affichée à côté",
    pages: [{ id: "bibliotheque", label: "Bibliothèque" }, { id: "info-client", label: "Chiffrage" }],
    quoi: "Le champ « taux de marge (%) » prêtait à confusion : 50 % de marge sur le prix de vente donnait un prix × 2, alors qu'on raisonne naturellement en « coût × 1,5 ». La saisie devient un coefficient de vente : prix de vente HT = coût total × coefficient. La marge équivalente en % du prix de vente reste calculée et affichée (× 1,5 = 33,3 %, × 2 = 50 %), et c'est elle qui est figée dans les lignes de chiffrage pour l'audit et les futurs devis.",
    comment: "Bibliothèque → ouvrir un ouvrage → carte « Prix de vente calculé » → « Coefficient de vente (× coût) » (ex. 1,5) → Sauvegarder. Les ouvrages déjà renseignés en taux sont convertis à l'équivalent exact par le SQL sql/202609_chiffrage_coef_vente.sql (à lancer après 202609_chiffrage_devis_logement.sql) : aucun prix ne change. Un coefficient inférieur à 1 est refusé (vente à perte).",
  },
  {
    date: "2026-09-14",
    type: "nouveaute",
    titre: "Chiffrage : prix calculés depuis la bibliothèque, un devis par logement, zones et marge",
    pages: [{ id: "info-client", label: "Chiffrage" }, { id: "bibliotheque", label: "Bibliothèque" }, { id: "admin", label: "Réglages" }],
    quoi: "Profero devient la source du prix. Dans la Bibliothèque, chaque ouvrage affiche son coût matériaux (quantités × prix d'achat), son coût de main-d'œuvre (cadence × taux horaire moyen des Réglages), son coût total, son taux de marge cible (modifiable, en % du prix de vente) et le prix de vente HT qui en découle : prix = coût ÷ (1 − marge). Un ouvrage sans cadence, sans marge, avec un matériau sans prix, ou sans matériau non confirmé « main-d'œuvre seule » est signalé « prix incalculable ». Côté Chiffrage, un projet représente désormais UN logement (référence + type) et un futur devis ; la fiche porte le client structuré (société, contact, adresse de facturation), l'adresse du chantier, l'objet, les dates et la TVA du devis. Chaque ouvrage s'ajoute autant de fois que nécessaire, chacun dans sa zone (Cuisine, Salle de bains, Chambre 1…), avec son prix figé au moment de l'ajout : changer la bibliothèque ne modifie jamais un devis existant. Le devis s'organise LOT → ZONE → OUVRAGES avec totaux HT, TVA, TTC, coûts, marge en € et taux de marge global réel, et une liste de ce qui manque avant de le considérer prêt.",
    comment: "Réglages → Taux : le « Taux horaire moyen (prévisionnel) » sert de coût horaire de référence (aucun prix calculé tant qu'il est vide) ; nouveau réglage « TVA par défaut du chiffrage ». Bibliothèque → ouvrir un ouvrage : carte « Prix de vente calculé » (coût direct complémentaire, taux de marge, case « main-d'œuvre seule »), état complet/incomplet et alertes. Chiffrage → Client & projet : cartes Client, Chantier & logement (bouton « Reprendre l'adresse de visite »), Devis (TVA à choisir) ; les anciens projets à plusieurs logements sont signalés « à vérifier » sans découpage automatique. Chiffrage → Ouvrages : choisir la zone puis « Ajouter » sur un ouvrage de la bibliothèque (cliquable plusieurs fois) ; sur chaque ligne : zone, quantité, unité, prix figé (cadenas, cliquer pour le détail), TVA, ⟳ « Actualiser depuis la bibliothèque » (affiche les différences puis demande confirmation, ligne par ligne) et corbeille (ne retire que cette ligne). Dupliquer demande la référence du nouveau logement et recopie tout, prix figés compris. Export : « Dossier PDF (client) » et Word sans coûts ni marge ; « Synthèse interne PDF » avec coûts, marge et points bloquants. Nécessite le SQL sql/202609_chiffrage_devis_logement.sql (un bandeau rouge l'indique sinon).",
  },
  {
    date: "2026-09-14",
    type: "nouveaute",
    titre: "Chiffrage : stylet sur tablette, budget & délai, bibliothèque, vidéos et nouveau PDF",
    pages: [{ id: "info-client", label: "Chiffrage" }],
    quoi: "La page Chiffrage devient un vrai carnet de visite pour tablette. Le client & projet porte maintenant le budget annoncé et le délai souhaité (avec l'écart budget/estimation calculé automatiquement). Les notes s'écrivent au stylet sur des pages manuscrites, et l'onglet Plan & côtes accueille des croquis à main levée. L'onglet Ouvrages affiche directement les ouvrages codés de la page Bibliothèque (libellé commençant par un code, ex. « D-001 : … »), groupés par lot ; les anciens ouvrages du chiffrage sont masqués et restent accessibles d'un clic. Les photos acceptent aussi les vidéos, chacune avec un titre et un commentaire. Enfin, l'export PDF est entièrement refait au design des autres documents Profero (même en-tête que le prévisionnel et la fiche opération).",
    comment: "Chiffrage → Client & projet : carte « Budget & délai ». Notes → bouton « Stylet » : une page se crée, on écrit directement ; le mode « Stylet seul » laisse le doigt faire défiler (paume posée sans risque), « Doigt + stylet » dessine aussi au doigt ; stylo, marqueur, gomme, couleurs, annuler/rétablir. Plan & côtes → « Nouveau croquis » (fond grille, lignes ou blanc). Ouvrages → la liste est celle de la bibliothèque, par lot (couleur et préfixe du lot, code en badge) : cocher un ouvrage l'ajoute au projet, puis quantité, unité et prix se saisissent sur la ligne ; « Anciens ouvrages (n) » ré-affiche l'ancienne liste du chiffrage et son bouton « Gérer ». Photos & vidéos → « Filmer » ou « Importer » (50 Mo max par vidéo), titre et commentaire sous chaque média, lecture dans la visionneuse. Export → « Exporter le dossier PDF » : client & projet, notes + pages manuscrites, ouvrages par lot avec estimation et écart budget, côtes, plans, croquis, photos (les vidéos figurent par titre et lien). Nécessite d'avoir lancé le SQL sql/202609_chiffrage_v2.sql dans Supabase (un bandeau l'indique sinon).",
  },
  {
    date: "2026-09-11",
    type: "amelioration",
    titre: "Phasage : tous les comptes rendus d'une tâche, aussi en vue Liste",
    pages: [{ id: "phasage-v2", label: "Phasage" }],
    quoi: "En vue Liste, le bouton « compte rendu » d'une tâche n'ouvrait que le dernier rapport la concernant. Il ouvre maintenant l'historique complet, comme en vue Chronologique : on voit d'un coup d'œil toutes les journées où la tâche a été déclarée, par qui, avec quel statut et quelles remarques.",
    comment: "Phasage → vue Liste → survoler une tâche → cliquer sur l'icône document (le chiffre à côté indique le nombre de comptes rendus quand il y en a plusieurs). La fenêtre liste les rapports du plus récent au plus ancien, avec pour chacun la ligne de la tâche (statut, heures, avancement, remarque) et la remarque générale du rapport.",
  },
  {
    date: "2026-09-10",
    type: "nouveaute",
    titre: "Validation fin de journée : basculer des heures vers un autre chantier",
    pages: [{ id: "validation", label: "Validation fin de journée" }],
    quoi: "Quand un ouvrier déclare toute sa journée sur un chantier alors qu'il en a passé une partie ailleurs, le conducteur peut maintenant déplacer tout ou partie des heures d'une ligne vers le bon chantier, sans rien ressaisir ni perdre la trace de la déclaration d'origine.",
    comment: "Ouvrir le rapport → sur la ligne concernée, cliquer sur la flèche ⇄ (à côté de « splitter ») → choisir le chantier de destination et le nombre d'heures à basculer. Les heures rejoignent le rapport du même ouvrier, même jour, sur ce chantier (créé s'il n'existe pas) ; il apparaît « En attente » dans la liste : l'ouvrir pour rattacher la tâche à son plan et le valider. Le reste des heures demeure sur la ligne d'origine. Le trajet du jour se répartit automatiquement au temps passé entre les chantiers. Si le rapport est déjà validé, cliquer d'abord sur « Corriger ». Les lignes concernées portent un badge « basculées ailleurs » / « reçue de … » pour garder l'historique.",
  },
  {
    date: "2026-09-09",
    type: "amelioration",
    titre: "Le Chemin de fer déménage dans la page Opérations",
    pages: [{ id: "operations", label: "Opérations" }],
    quoi: "Tout ce qui concerne une opération est maintenant au même endroit : la page Chemin de fer disparaît du menu et devient un onglet de la fiche opération, à côté de la synthèse financière. Une entrée de menu en moins, zéro fonction en moins.",
    comment: "Ouvrir Opérations → choisir une opération → onglet « Chemin de fer ». On y retrouve la frise complète à l'identique : zoom semaines/jours, détail et décalage des groupes, et les trois exports PDF (chemin de fer paysage, prévisionnel client, dossier de plans).",
  },
  {
    date: "2026-09-09",
    type: "nouveaute",
    titre: "Nouvelle page Opérations : la fiche consolidée d'un immeuble, avec sa marge",
    pages: [{ id: "operations", label: "Opérations" }],
    quoi: "Jusqu'ici les chiffres n'existaient que chantier par chantier. La page Opérations additionne tous les logements d'une même opération pour donner la vision d'ensemble : vendu HT, coûts réels (main-d'œuvre, matériaux, frais généraux), marge nette et prévisionnelle, avancement global et diagramme financier consolidé.",
    comment: "Dans le menu, ouvrir « Opérations » : chaque carte résume une opération (logements, avancement, vendu, marge). Cliquer dessus ouvre sa fiche : cartes financières agrégées, barre de décomposition du vendu, tableau des logements (une ligne par chantier, cliquable pour ouvrir sa fiche) et diagramme financier cumulé de toute l'opération. Les chiffres sont calculés par le même module que la fiche Chantier — rien n'est recalculé différemment. Le bouton PDF en haut de la fiche génère la « Fiche opération » au design des documents Profero : chiffres clés, tableau prévisionnel vs réel, décomposition du vendu et détail par logement — document interne (il contient les marges), à ne pas envoyer au client.",
  },
  {
    date: "2026-09-08",
    type: "amelioration",
    titre: "Commandes du chantier : barre de recherche dans la liste des lignes",
    pages: [{ id: "phasage-v2", label: "Phasage" }],
    quoi: "Sur les gros chantiers, la fenêtre « Commandes du chantier » peut compter plus d'une centaine de lignes : la recherche permet de retrouver instantanément une ligne sans faire défiler toute la liste.",
    comment: "Dans le Phasage, cliquer sur la carte Commandes ouvre la fenêtre : une barre de recherche reste visible en haut de la liste. Elle filtre au fil de la frappe sur le libellé, le fournisseur, le lot et l'ouvrage. Le compteur indique le nombre de lignes trouvées, et le total en bas s'ajuste aux résultats filtrés.",
  },
  {
    date: "2026-09-07",
    type: "nouveaute",
    titre: "Espace ouvrier : les chefs d'équipe voient le planning de toutes les équipes",
    pages: [], // espace ouvrier (mobile), hors pages bureau
    quoi: "Un chef d'équipe (responsable déclaré d'une équipe dans Réglages → Équipes) peut consulter le planning de son équipe et de toutes les autres depuis son espace ouvrier, en lecture seule. Une équipe peut désormais avoir plusieurs responsables (ex. Venceslas et Steven sur la même équipe) : chacun bénéficie de cette vue. Rien ne change pour les autres ouvriers, et le chef n'a accès à aucune donnée financière.",
    comment: "Dans l'onglet Planning de l'espace ouvrier, un sélecteur « Moi / Mon équipe / Tout » apparaît automatiquement pour les responsables d'équipe. « Mon équipe » montre les chantiers où au moins un membre de son équipe est planifié ; « Tout » montre, jour par jour, chaque chantier avec les personnes présentes, en pastilles aux couleurs de leur équipe, avec des puces pour filtrer par équipe. Sous chaque chantier, la liste des tâches du jour précise qui doit faire quoi (« — tous » quand la tâche concerne toute l'équipe du chantier). La navigation de semaine reste la même.",
  },
  {
    date: "2026-09-07",
    type: "amelioration",
    titre: "Inventaire des équipes : audit mensuel et import du Google Sheets",
    pages: [{ id: "inventaire-equipes", label: "Inventaire des équipes" }],
    quoi: "L'audit mensuel du matériel se fait directement dans l'application : chaque outil est pointé présent ou manquant et son état est constaté (neuf, bon état, mauvais état, hors service). L'inventaire existant sur Google Sheets s'importe en quelques clics, sans ressaisie.",
    comment: "Sur la fiche d'un ouvrier, « Démarrer l'audit » liste tous ses outils : on pointe chacun Présent ou Manquant et on corrige l'état constaté ; la clôture n'est possible que quand tout est pointé, et met à jour les fiches outils. Les ouvriers non audités depuis plus d'un mois portent une pastille « à auditer », et l'historique des audits reste consultable. Le bouton « Importer » lit un export Excel du Google Sheets (un onglet par ouvrier ou une colonne Ouvrier), reconnaît les colonnes automatiquement et met à jour les codes déjà connus.",
  },
  {
    date: "2026-09-07",
    type: "nouveaute",
    titre: "Inventaire des équipes : qui détient quel matériel",
    pages: [{ id: "inventaire-equipes", label: "Inventaire des équipes" }],
    quoi: "Savoir à tout moment quel matériel est entre les mains de chaque ouvrier. Chaque outil est identifié par le code unique inscrit dessus (ex. P-012 sur une perceuse), et la recherche répond directement à « qui a cet outil ? ».",
    comment: "La page liste tous les ouvriers du planning ; un clic sur un ouvrier affiche le matériel mis à sa disposition, avec le code de chaque outil bien en évidence, son état (bon, usé, hors service) et sa date de remise. Le matériel non affecté apparaît dans « Au dépôt ». On ajoute un outil avec « Nouvel outil », et la barre de recherche retrouve un outil par son code, son nom ou son détenteur.",
  },
  {
    date: "2026-09-07",
    type: "nouveaute",
    titre: "Journal des MAJ : cette page",
    pages: [{ id: "journal-maj", label: "Journal des MAJ" }],
    quoi: "Savoir ce qui a changé dans l'application sans avoir à le découvrir par hasard : chaque mise à jour est expliquée ici, avec son utilité et son fonctionnement.",
    comment: "La page liste les mises à jour de la plus récente à la plus ancienne, regroupées par mois. On peut filtrer par type (nouveauté, amélioration, correctif), chercher un mot-clé, et cliquer sur la page concernée pour l'ouvrir directement. Les entrées publiées depuis votre dernière visite portent une pastille « Nouveau ».",
  },
  {
    date: "2026-09-07",
    type: "amelioration",
    titre: "Notes & To-do : notes détaillées, mises à jour horodatées et emails",
    pages: [{ id: "notes-todo", label: "Notes & To-do" }],
    quoi: "Une tâche peut maintenant porter tout son contexte : une note descriptive, plusieurs assignés, et un fil de mises à jour daté. Les personnes concernées sont prévenues par email, y compris du détail de la tâche.",
    comment: "Sur chaque tâche : un champ note pour décrire le travail, des boutons d'échéance rapide (aujourd'hui, demain, cette semaine…), et la possibilité d'assigner plusieurs personnes. Chaque ajout de mise à jour est horodaté et déclenche un email aux assignés. L'email d'assignation reprend la note et les détails de la tâche.",
  },
  {
    date: "2026-09-07",
    type: "amelioration",
    titre: "Bilan de semaine : marge nette générée par chantier",
    pages: [{ id: "bilan-semaine", label: "Bilan de semaine" }],
    quoi: "Voir en un coup d'œil non seulement le chiffre d'affaires généré dans la semaine par chaque chantier, mais aussi la marge nette que cette production a réellement dégagée.",
    comment: "Dans l'accordéon financier du bilan, la marge nette générée s'affiche à côté du CA généré pour chaque chantier. Les chantiers qui n'ont pas encore de snapshot hebdomadaire sont désormais comptés dans le généré (au lieu d'être ignorés).",
  },
  {
    date: "2026-09-04",
    type: "nouveaute",
    titre: "Planning semaine : déplacer des tâches vers une autre semaine",
    pages: [{ id: "planning", label: "Planning semaine" }],
    quoi: "Quand un chantier glisse, plus besoin de tout re-saisir : les tâches planifiées se déplacent vers une autre semaine en quelques clics. Un mode « tout le jour » permet aussi de déplacer une journée entière.",
    comment: "Depuis la cellule du planning, choisir le déplacement vers une autre semaine : les tâches sont recopiées sur la semaine cible et retirées de la semaine d'origine, en gardant leur lien avec le phasage. Le mode « tout le jour » sélectionne d'un coup toutes les tâches du jour.",
  },
  {
    date: "2026-09-04",
    type: "correctif",
    titre: "Validation : garde-fou sur les heures saisies",
    pages: [{ id: "validation", label: "Validation fin de journée" }],
    quoi: "Éviter qu'une faute de frappe (ex. 80 h au lieu de 8 h) ne fausse les pointages, la paie et les coûts de main-d'œuvre.",
    comment: "À la validation d'un compte rendu, les heures manifestement anormales sont détectées et signalées avant l'enregistrement : il faut confirmer ou corriger la valeur.",
  },

  // ── AOÛT 2026 ──────────────────────────────────────────────────────────────
  {
    date: "2026-08-28",
    type: "nouveaute",
    titre: "Planning de référence (baseline)",
    pages: [{ id: "planning", label: "Planning semaine" }],
    quoi: "Figer une « photo » du planning à un instant donné pour pouvoir comparer ensuite le prévu initial et le réalisé, et mesurer les dérives.",
    comment: "Un panneau « Planning de référence » permet de prendre une version de référence du planning et de consulter les versions figées. Les affectations sont verrouillables individuellement pour protéger ce qui est acté.",
  },
  {
    date: "2026-08-28",
    type: "nouveaute",
    titre: "Ressources & indisponibilités : la capacité réelle dans le planning",
    pages: [{ id: "admin", label: "Réglages" }, { id: "planning", label: "Planning semaine" }],
    quoi: "Le planning connaît maintenant la disponibilité réelle de chacun : absences, congés et capacité par jour. On ne peut plus surcharger quelqu'un sans le voir.",
    comment: "Dans Réglages, un écran « Ressources et indisponibilités » liste les ouvriers avec leurs absences. À l'affectation dans le planning, la capacité restante de la journée est calculée en tenant compte du rythme 4 j/5 j et des absences (une absence journée met le plafond à 0 h).",
  },
  {
    date: "2026-08-28",
    type: "nouveaute",
    titre: "Prévisionnel client : document PDF généré depuis le planning",
    pages: [{ id: "phasage-v2", label: "Phasage" }, { id: "operations", label: "Opérations" }],
    quoi: "Remettre au client un calendrier prévisionnel propre et professionnel, sans le refaire à la main : il est généré depuis le planning réel, chantier par chantier ou pour toute l'opération.",
    comment: "Export PDF « Prévisionnel » avec une mise en page premium : frise horizontale « Vue d'ensemble », chips de synthèse, détail par groupe de tâches. Le Chemin de fer propose aussi un PDF « Dossier de plans » de l'opération, pensé comme document client.",
  },
  {
    date: "2026-08-27",
    type: "amelioration",
    titre: "Compte rendu ouvrier : rattrapage d'un jour manqué et envoi fiabilisé",
    pages: [],
    quoi: "Un ouvrier qui a oublié son compte rendu la veille peut le rattraper lui-même, et l'envoi fonctionne du premier coup (fini le « il faut envoyer deux fois »).",
    comment: "Dans l'espace ouvrier, le compte rendu accepte la saisie d'un jour passé non déclaré. Le bouton d'envoi a été fiabilisé : l'enregistrement est confirmé ou l'erreur est affichée, sans état intermédiaire trompeur.",
  },
  {
    date: "2026-08-25",
    type: "nouveaute",
    titre: "Espace ouvrier : section « À reprendre »",
    pages: [],
    quoi: "Les tâches commencées mais non terminées ne disparaissent plus : elles restent visibles pour l'équipe jusqu'à ce qu'elles soient vraiment finies.",
    comment: "Sur le tableau de bord de l'espace ouvrier, une section « À reprendre » liste les tâches entamées non soldées. L'équipe affichée vient du planning (pas seulement du phasage), et ces tâches sont proposées directement dans le formulaire de compte rendu.",
  },
  {
    date: "2026-08-22",
    type: "nouveaute",
    titre: "Barre « Mes tâches » sur toutes les pages",
    pages: [{ id: "notes-todo", label: "Notes & To-do" }],
    quoi: "Ne plus perdre de vue ses tâches assignées : elles suivent l'utilisateur partout dans l'application, sans devoir retourner sur la page Notes & To-do.",
    comment: "Une bulle persistante en bas d'écran affiche les tâches qui vous sont assignées, sur toutes les pages Rénovation. Un clic ouvre le détail ; un lien renvoie vers la page Notes & To-do complète.",
  },
  {
    date: "2026-08-21",
    type: "nouveaute",
    titre: "Espace ouvrier : onglet Chantiers avec plans et heures",
    pages: [{ id: "plans", label: "Plans" }],
    quoi: "L'ouvrier accède depuis son téléphone aux vrais plans du chantier et voit où en sont les heures : vendues vs réelles, ouvrage par ouvrage.",
    comment: "Nouvel onglet « Chantiers » dans l'espace ouvrier : chaque chantier affiche ses plans (les mêmes que la page Plans du bureau) et un comparatif heures vendues / heures réelles par ouvrage. Le planning ouvrier permet aussi de naviguer librement entre les semaines.",
  },
  {
    date: "2026-08-21",
    type: "amelioration",
    titre: "Connexion : arrivée sur la première page autorisée",
    pages: [],
    quoi: "Un utilisateur au périmètre restreint n'atterrit plus sur « Accès refusé » à la connexion.",
    comment: "À l'ouverture de l'application, si le rôle n'a pas accès au tableau de bord, on bascule automatiquement sur la première page autorisée de son profil.",
  },
  {
    date: "2026-08-20",
    type: "nouveaute",
    titre: "Rythme de travail 4 jours / 5 jours",
    pages: [{ id: "planning", label: "Planning semaine" }, { id: "heures-salaries", label: "Heures des salariés" }],
    quoi: "L'application intègre l'alternance de l'entreprise : semaines impaires à 4 jours, semaines paires à 5 jours (depuis le 24/08/2026). Capacités, plannings et heures attendues suivent automatiquement.",
    comment: "Le rythme est calculé depuis le numéro de semaine ISO, à un seul endroit du code. Le planning, la capacité par jour et les heures attendues par salarié s'adaptent sans réglage manuel.",
  },
  {
    date: "2026-08-19",
    type: "amelioration",
    titre: "Phasage : KPI « Marge prévisionnelle »",
    pages: [{ id: "phasage-v2", label: "Phasage" }],
    quoi: "Connaître dès le phasage la marge attendue du chantier, avant même le premier jour de travaux.",
    comment: "Un indicateur calcule la marge prévisionnelle : vendu moins déboursé prévu (main-d'œuvre + matériaux) moins frais généraux prévus. Il s'affiche dans le bandeau KPI du phasage.",
  },
  {
    date: "2026-08-16",
    type: "amelioration",
    titre: "Biblio. ouvrages : dupliquer et réordonner",
    pages: [{ id: "bibliotheque", label: "Biblio. ouvrages" }],
    quoi: "Créer une déclinaison d'un ouvrage existant sans tout re-saisir, et ranger les sous-tâches dans le bon ordre d'exécution.",
    comment: "Bouton « Dupliquer » sur chaque ouvrage de la bibliothèque, et flèches haut/bas pour réordonner les sous-tâches.",
  },
  {
    date: "2026-08-08",
    type: "nouveaute",
    titre: "Socle technique IA : fondations posées",
    pages: [{ id: "admin", label: "Réglages" }],
    quoi: "Préparer l'arrivée de fonctions IA dans l'application (analyses, propositions) avec des garde-fous : chaque appel est journalisé, plafonné, et un coupe-circuit permet de tout arrêter.",
    comment: "Une route serveur unique /api/ai centralise les appels IA : authentification, autorisation par rôle, journalisation en base (table ia_jobs), quotas par utilisateur et par jour, plafonds de coût et coupe-circuit global. Une tâche de test « ping » permet de vérifier la chaîne de bout en bout.",
  },

  // ── JUILLET 2026 ───────────────────────────────────────────────────────────
  {
    date: "2026-07-30",
    type: "nouveaute",
    titre: "Factures de situation sur l'avancement",
    pages: [{ id: "chantiers", label: "Chantiers" }, { id: "admin", label: "Réglages" }],
    quoi: "Ne plus rater une facturation intermédiaire : quand l'avancement d'un chantier franchit un seuil, l'application le signale et prévient les bonnes personnes par email.",
    comment: "Les seuils d'avancement sont réglables dans Réglages (onglet « Fact. de situation »), ainsi que les rôles notifiés. Sur la frise du chantier, les jalons de facturation apparaissent sur l'avancement ; le franchissement déclenche un email automatique.",
  },
  {
    date: "2026-07-29",
    type: "nouveaute",
    titre: "Contrôles de fin de groupe : la qualité tracée sur chantier",
    pages: [{ id: "phasage-v2", label: "Phasage" }, { id: "visite", label: "Visites chantier" }],
    quoi: "Chaque groupe de tâches terminé doit être contrôlé : l'application le rappelle, garde la trace du contrôle et suit les réserves jusqu'à leur levée. C'est ce qui alimente le sommet « Qualité » du QCD.",
    comment: "Un jalon de contrôle est créé automatiquement à la fin de chaque groupe. L'écran de contrôle (pensé mobile d'abord) fonctionne par exception : tout est réputé conforme, on ne saisit que les réserves. Les réserves ont une levée explicite, une ancienneté et des compteurs ; un groupe non contrôlé est signalé en rouge (obligatoire mais jamais bloquant).",
  },
  {
    date: "2026-07-28",
    type: "nouveaute",
    titre: "Fiche chantier : bandeau QCD et frise de cycle de vie",
    pages: [{ id: "chantiers", label: "Chantiers" }],
    quoi: "Lire l'état de santé d'un chantier en une seconde : Qualité / Coût / Délai en tête de fiche, et une frise des 6 phases de vie (devis → SAV) pour savoir où on en est.",
    comment: "Le bandeau QCD calcule automatiquement chaque sommet (avec correction manuelle possible). La frise affiche les 6 phases avec validation d'étape par action et pièces jointes sur chaque étape ; la phase Travaux est branchée sur l'avancement réel des groupes.",
  },
  {
    date: "2026-07-28",
    type: "amelioration",
    titre: "Brouillons automatiques : plus de saisie perdue",
    pages: [],
    quoi: "Une mise à jour de l'application ou une fausse manipulation ne fait plus perdre un formulaire en cours de saisie.",
    comment: "Les saisies sont protégées par un garde global : l'application ne se recharge jamais pendant qu'un champ est en cours d'édition, et les formulaires longs conservent un brouillon local restauré à la réouverture.",
  },
  {
    date: "2026-07-28",
    type: "nouveaute",
    titre: "Bilan de semaine : la page complète",
    pages: [{ id: "bilan-semaine", label: "Bilan de semaine" }],
    quoi: "Un point hebdomadaire multi-chantiers en une page : finances par chantier, points d'attention automatiques, projections, et un PDF de restitution propre à diffuser.",
    comment: "La page se choisit une semaine et charge tout : accordéon financier par chantier (marge, dérive par lot, KPI cliquables avec leur méthode de calcul), points d'attention détectés automatiquement (dérive de marge, stagnation, compte rendu manquant, lot démarrant sous 15 jours sans commande), bloc projections (marge à terminaison, reste à faire, situation à facturer), saisie des blocages et de la semaine suivante, export PDF sélectif. Un instantané financier est archivé chaque vendredi soir pour suivre l'évolution.",
  },
  {
    date: "2026-07-27",
    type: "nouveaute",
    titre: "Équipes et groupes types : les référentiels de l'exécution",
    pages: [{ id: "admin", label: "Réglages" }, { id: "phasage-v2", label: "Phasage" }],
    quoi: "Standardiser la façon dont les chantiers s'exécutent : 12 étapes types (démolition → finitions) et des équipes nommées avec responsable, membres et intervenants externes. L'affectation d'une équipe sur un groupe se fait en un clic.",
    comment: "Deux référentiels dans Réglages : « Groupes types » (les 12 étapes, avec équipe par défaut et ouvriers prioritaires) et « Équipes » (responsable, membres, marquage externe, date de disponibilité). Dans le phasage, les groupes chrono sont semés depuis les groupes types et le bouton « Affecter l'équipe » pré-remplit les ouvriers sur toutes les tâches du groupe.",
  },
  {
    date: "2026-07-27",
    type: "nouveaute",
    titre: "Comptes sans adresse email",
    pages: [{ id: "admin", label: "Réglages" }],
    quoi: "Créer un compte à un ouvrier qui n'a pas d'adresse email : un identifiant et un mot de passe suffisent.",
    comment: "Dans Réglages, la création de compte accepte un simple identifiant (ex. « jp ») ; l'application gère l'email technique en interne. Une vraie adresse email peut être rattachée plus tard sans rien casser.",
  },
  {
    date: "2026-07-26",
    type: "amelioration",
    titre: "Plans : dessin plus complet et plus fiable",
    pages: [{ id: "plans", label: "Plans" }],
    quoi: "Dessiner des plans plus proches de la réalité du chantier : doublages, cloisons, portes battantes avec leur débattement, largeur des fenêtres… et ne plus jamais perdre un dessin.",
    comment: "Nouveaux outils : doublages/cloisons, gomme par tronçon, saisie des longueurs au clavier, portes battantes 70/80/90 poussant gauche/droite avec arc de débattement. L'éditeur sauvegarde automatiquement (2 s après la dernière modification et à la fermeture).",
  },
  {
    date: "2026-07-23",
    type: "nouveaute",
    titre: "Planning ↔ Phasage : les tâches se planifient depuis le planning",
    pages: [{ id: "planning", label: "Planning semaine" }, { id: "phasage-v2", label: "Phasage" }],
    quoi: "Le planning et le phasage parlent enfin ensemble : on planifie les tâches du phasage directement dans la grille semaine, et les dates prévues se synchronisent toutes seules.",
    comment: "Dans la cellule du planning, un sélecteur propose les tâches du phasage du chantier ; la date prévue de la tâche devient son premier jour planifié. La durée s'appuie sur les heures vendues et se répartit selon le nombre d'ouvriers. Une ligne « Charge » par ouvrier et par jour montre la capacité réelle (rythme 4 j/5 j) et signale les surcharges. L'export PDF tient sur une page, sans les chantiers vides.",
  },
  {
    date: "2026-07-15",
    type: "nouveaute",
    titre: "Vue « Chronologique » du phasage",
    pages: [{ id: "phasage-v2", label: "Phasage" }],
    quoi: "Organiser le chantier comme il va se dérouler : les tâches se rangent dans des groupes ordonnés (corps d'état), avec jalons, dates et export PDF du planning chantier par groupe.",
    comment: "La vue chrono permet le glisser-déposer des tâches entre groupes, le réordonnancement, la multi-sélection, les jalons datés entre tâches, et un encart « Où en est-on ? » (avancement + prochaines tâches). Une template globale des corps d'état pré-génère les groupes ; le Gantt affiche les lots repliables et les jalons.",
  },
  {
    date: "2026-07-15",
    type: "nouveaute",
    titre: "Page « Heures des salariés » : la préparation de la paie",
    pages: [{ id: "heures-salaries", label: "Heures des salariés" }],
    quoi: "Une vue par salarié pour préparer la paie : heures pointées, base 39 h, heures supplémentaires, trajets. Fini le recomptage à la main depuis les comptes rendus.",
    comment: "La page agrège le registre de pointages (alimenté par les validations de fin de journée) par ouvrier et par semaine. Les trajets sont répartis au centime près et pondérés par le temps passé sur chaque chantier. Un outil de diagnostic dans Réglages (onglet Pointages) compare jour par jour le registre et le déclaré, et répare les écarts.",
  },
  {
    date: "2026-07-17",
    type: "amelioration",
    titre: "Saisie commande : anti-doublons et lecture IA plus fiable",
    pages: [{ id: "capture-cmd", label: "Saisie commande" }],
    quoi: "Éviter de compter deux fois le même bon de livraison, et mieux lire les documents difficiles (PDF, gros BL, remises).",
    comment: "À l'enregistrement, l'application détecte si un document identique existe déjà et le signale. L'analyse IA convertit les PDF en images pour les lire, force les prix en HT, ignore les lignes non livrées et répartit les remises globales sur les lignes.",
  },
  {
    date: "2026-07-08",
    type: "nouveaute",
    titre: "Phasage : vue « Prévisionnel » calendrier client",
    pages: [{ id: "phasage-v2", label: "Phasage" }],
    quoi: "Montrer au client un calendrier prévisionnel lisible de son chantier, exportable en PDF.",
    comment: "Une vue dédiée du phasage présente le déroulé sous forme de calendrier orienté client, avec export PDF.",
  },
  {
    date: "2026-07-03",
    type: "nouveaute",
    titre: "Encours fournisseurs : les dépenses par fournisseur et par mois",
    pages: [{ id: "encours-fournisseurs", label: "Encours fournisseurs" }],
    quoi: "Savoir combien on doit à chaque fournisseur et quand : les dépenses sont regroupées par mois d'échéance de paiement (comptant, 30 jours, 30 jours fin de mois).",
    comment: "La page distingue « à payer » et « payé comptant », détaille les documents (BL, tickets, factures) par mois, compare saisi et facturé avec l'écart, et s'exporte en PDF. Un email récapitulatif part chaque vendredi soir aux destinataires choisis dans Réglages.",
  },
  {
    date: "2026-07-03",
    type: "nouveaute",
    titre: "Menu latéral : onglets réorganisables",
    pages: [],
    quoi: "Chacun range le menu à sa façon : les pages les plus utilisées en haut.",
    comment: "Un bouton crayon en bas du menu active le glisser-déposer des onglets. L'ordre est mémorisé par utilisateur et synchronisé : on le retrouve d'un appareil à l'autre.",
  },
];
